version: '3.1'
services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  odoo:
    image: odoo:17
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - DB=data
    volumes:
      - odoo_data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
    command: odoo --db_host=db --db_user=odoo --db_password=odoo --database=data --proxy-mode

# Deploy: Quick Tunnel (miễn phí, không cần domain)
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    environment:
      - NGROK_AUTHTOKEN=3CXdoaaOW0blLgxVXjQ6lR9AkPa_Y9E1NdoPySEfhuQS4EGS
    command:
      - "http"
      - "--domain=breeding-cabbie-stick.ngrok-free.dev"
      - "odoo:8069"
    depends_on:
      - odoo

volumes:
  db_data:
  odoo_data:
